version: "3.9"

services:
  db:
    image: postgres:15
    container_name: my_postgres_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: myuser
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "myuser", "-d", "my_fastapi_db"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  web:
    build: .
    container_name: my_fastapi_app
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://myuser:mypass@db:5432/my_fastapi_db
    ports:
      - "8080:80"
    volumes:
      - .:/app

volumes:
  postgres_data:
