# Generated by Django 5.1.7 on 2025-03-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BodyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('mass', models.FloatField()),
                ('position_x', models.FloatField()),
                ('position_y', models.FloatField()),
                ('position_z', models.FloatField()),
                ('velocity_x', models.FloatField()),
                ('velocity_y', models.FloatField()),
                ('velocity_z', models.FloatField()),
                ('trajectory_json', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
